import { CheckoutFormComponent, CheckoutSummaryComponent, LayoutComponent } from "@hype-charms/client";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { eventheader_content, subheader_content, header_content } from "../../constants/header";
import { useCallback } from "react";
import { useHeaderControls } from "../../hooks/header-controls";

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: {} }
}
const Home: NextPage = () => {
  const handleSubmit = useCallback((email: string) => {
    console.log(email);
  }, [])
  const { handleCartClick, handleProfileClick } = useHeaderControls();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <script type="text/javascript" src="/scripts/font-awesome.js" defer></script>
      </Head>
      <LayoutComponent onCartClick={handleCartClick} onProfileClick={handleProfileClick} eventheader_content={eventheader_content} subheader_content={subheader_content} header_content={header_content}>
        <div className="flex flex-row w-screen h-screen items-center">
          <div className="flex-1" />
          <div className="flex-1 px-20">
            <div className="h-[10rem]">
              <CheckoutSummaryComponent cart={[]} />
            </div>
            <CheckoutFormComponent onSubmit={handleSubmit} />
          </div>
        </div>
      </LayoutComponent>
    </>
  );
};

export default Home;