import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { LayoutComponent, Module, ProductDisplayComponent } from "@hype-charms/client"
import { eventheader_content, header_content, subheader_content } from "../constants/header";
import { MainComponent } from "../components/main.component";
import { HypeItemReference } from "@hype-charms/types";
import { useHeaderControls } from "../hooks/header-controls";

export const getServerSideProps: GetServerSideProps = async () => {
  // const products: HypeItemReference[] | null = await shop.products.fetchAllProducts(100)
  //   .then(data => data.map((data) => MapShopifyProductReferencesToHypeItemReference(data.node)))
  //   .catch(err => {
  //     console.log(err);
  //     return null
  //   });
  const products = null;
  return { props: { products: products } }
}
const Home: NextPage<{ products: HypeItemReference[] | null }> = ({ products }) => {
  const { handleCartClick, handleProfileClick } = useHeaderControls();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutComponent
        onCartClick={handleCartClick}
        onProfileClick={handleProfileClick}
        eventheader_content={eventheader_content}
        subheader_content={subheader_content}
        header_content={header_content}>
        <div className="pt-3">
          <MainComponent packs={[]} products={[]} />
          <Module title="Featured" href="/">
            {products && <div className="flex flex-row justify-start gap-6 overflow-x-scroll py-8">
              {products.map((product, idx) => <ProductDisplayComponent key={idx} size="md" product={product} id="" />)}
            </div>}
          </Module>
        </div>
      </LayoutComponent>
      <div style={{ height: "100vh" }}></div>
    </>
  );
};

export default Home;
