import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { LayoutComponent, Module, ShopifyProductDisplayComponent } from "@hype-charms/client"
import { eventheader_content, header_content, subheader_content } from "../constants/header";
import { MainComponent } from "../components/main.component";
import { ShopifyItemReference } from "@hype-charms/types";

export const getServerSideProps: GetServerSideProps = async () => {
  // const products = await shop.products.fetchAllProducts(100).catch();
  const products = null;
  return { props: { products: products } }
}
const Home: NextPage<{ products: { node: ShopifyItemReference }[] | null }> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <script type="text/javascript" src="/scripts/font-awesome.js" defer></script>
      </Head>
      <LayoutComponent eventheader_content={eventheader_content} subheader_content={subheader_content} header_content={header_content}>
        <div className="pt-3">
          <Module>
            <MainComponent packs={[]} products={[]} />
          </Module>
          <Module title="Featured" href="/">
            {products && <div className="flex flex-row justify-start gap-6 overflow-x-scroll py-8">
              {products.map(({ node }, idx) => <ShopifyProductDisplayComponent key={idx} size="md" product={node} id="" />)}
            </div>}
          </Module>
        </div>
      </LayoutComponent>
      <div style={{ height: "100vh" }}></div>
    </>
  );
};

export default Home;
